### ISSUE TITLE
قسمت منو همیشه باز

### ISSUE THREAD

**Issue by hasanzade68** [rezaghz/persian-assistant#10]
اگه میشه قسمت منو همیشه رو حالت باز باشه تا خیلی ساده تر بشه رو موارد دلخواه جابجا شد...و نیاز نباشه همیشه روی قسمت سه خط کلیک کنیم. اینجوری امکانات نرم افزارم جلو چشممونه همیشه

**Comment by rezaghz** [comment]
سلام بله این رو یه بررسی کلی میکنیم اگه بهتر بود میزاریم که کلا باز باشه ، ولی بیشتر بخاطر این ، اینکارو کردم که همه چی تو چشم نباشه و کاربر هر چی که دنبالش هست رو انتخاب کنه ممنونم
