### ISSUE TITLE
همگام سازی

### ISSUE THREAD

**Issue by ali2bastami** [rezaghz/persian-assistant#12]

**Comment by ali2bastami** [comment]
امکان همگام سازی (sync) با تقویم گوگل و یا حتی تقویم مایکروسافت (outlook calendar) جهت درج رویدادها به/از لوتوس و تقویم گوگل یا مایکروسافت فراهم گردد. با تشکر

**Comment by rezaghz** [comment]
سلام ممنونم ازتون ، این issue داپلیکیت شده 
[https://github.com/rezaghz/loutos/issues/9](https://github.com/rezaghz/loutos/issues/9)
در ورژن های بعدی اضافه میشه .
