### ISSUE TITLE
افزودن اوقات شرعی و اذان

### ISSUE THREAD

**Issue by mimsadAlef** [rezaghz/persian-assistant#14]
سلام 
نرم افزار های مشابه قابلیت اذان گفتن و نمایش اوقات شرعی رو هم دارند که به نظرم نیاز هست

**Comment by rezaghz** [comment]
سلام خیلی ممنون ازتون ، این مورد هم به لیست فیچر ها اضافه شد ممنونم

**Comment by rezaghz** [comment]
سلام روزتون بخیر 
در نسخه جدید قابلیت اوقات شرعی 
 https://github.com/rezaghz/loutos/releases/tag/v1.1.0
اضافه شد
