### ISSUE TITLE
آموزش دولوپ کردنش رو میزارید؟

### ISSUE THREAD

**Issue by Amirrezaheydari81** [rezaghz/persian-assistant#15]
الان من روی لینوکس سورس رو آورم ولی نمیتونم دولوپ کنم میشه بگید باید دقیقا چیکار کنم نود هم نصب کردم

**Comment by Amirrezaheydari81** [comment]
روی localhost:9080 بالا اومده ولی صفحه سفید

**Comment by rezaghz** [comment]
سلام شبت بخیر 
دولوپ کردن این پروژه خیلی ساده است ، شما بعد از اینکه مراحل نصب پکیج های npm رو گذروندید 
فقط با کامند 
`npm run dev`

اپلیکیشن برای شما بیلد میشه و نمایش داده میشه و میتونید توسعه تون رو شروع کنید

**Comment by Amirrezaheydari81** [comment]
خب الان ی مشکلی دارم من css ها رو تغییر میدم وقتی رفرش می کنم پروژه رو انگاری کش شده و تغییری ایجاد نمیشه
