### ISSUE TITLE
خطا در محاسبهٔ اوقات شرعی

### ISSUE THREAD

**Issue by afshin-ir** [rezaghz/persian-assistant#19]
<div dir=rtl>
سلام.

شهر مشهد را که انتخاب می‌کنی، اوقات شرعی را با درصد خطای بالایی محاسبه می‌کند. 

روی حرف «ی» در نام استان هم یک همزهٔ زائد وجود دارد. الان این‌طور است: «رضوئ»

![image](https://user-images.githubusercontent.com/14938202/204307049-c27ce005-5f6f-49b8-8c03-bd8ca519e437.png)

**Comment by rezaghz** [comment]
سلام خیلی ممنون از گزاشتون تو ورژن 1.2.0 که الان دارم کار میکنم روش این مورد فیکس شده ، متاسفانه از دیتابیس که لیست شهر ها بود مختصات شهر مشهد به اشتباه یه شهر در آذربایجان غربی بود که من الان فیکسش کردم و تو آپدیت جدید میفرستم

**Comment by rezaghz** [comment]
مشکل حل شد دوست عزیز میتونید برنامه رو دانلود کنید، لطفا نسخه قبلی رو پاک کنین و نسخه جدید رو نصب کنین
